### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by manfi001** [MrJanD/bimmer2mqtt#1]
Hi,
installed latest bimmer_connected (0.10.4). when running bimmer2mqtt, I get "ModuleNotFoundError: No module named 'bimmer_connected.country_selector'"

**Comment by MrJanD** [comment]
Thanks, it shall work now. 
Publish a message to 
> _Mobility/CarName/cmd_

with a payload in the following order
> _'state', 'Your Username or Mail Address', 'Your Password', 'Your VIN'_

**Comment by manfi001** [comment]
Hi,
Unfortunately not working. Published with MQTTfx as described above and script stops with following output:

$ /home/pi/.local/bin/bimmer2mqtt.py
2022-12-05 21:12:16 INFO     Connected with result code 0
2022-12-05 21:12:22 INFO     car_execute: Mobility/CarName/cmd b"'state', 'bmw.530d@mail.link', 'password', 'VINxxxxxxxxxxxxxx'" #credentials modified. No idea, where this ^ **b** comes from 
2022-12-05 21:12:23 ERROR    Authentication error (invalid_client): Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
Traceback (most recent call last):
  File "/home/pi/.local/bin/bimmer2mqtt.py", line 149, in <module>
    mqtt_handler.run()
  File "/home/pi/.local/bin/bimmer2mqtt.py", line 63, in run
    self.client.loop_forever()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3556, in _handle_on_message
    callback(self, self._userdata, message)
  File "/home/pi/.local/bin/bimmer2mqtt.py", line 52, in car_execute
    returnData = sw.runCmd()
  File "/home/pi/.local/bin/bimmer2mqtt.py", line 75, in runCmd
    return self.get_status()
  File "/home/pi/.local/bin/bimmer2mqtt.py", line 98, in get_status
    return self.get_vehicle().data
  File "/home/pi/.local/bin/bimmer2mqtt.py", line 93, in get_vehicle
    asyncio.run(account.get_vehicles())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/account.py", line 89, in get_vehicles
    await self._init_vehicles()
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/account.py", line 67, in _init_vehicles
    vehicles_responses: List[httpx.Response] = [
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/account.py", line 68, in <listcomp>
    await client.get(
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    request = await auth_flow.__anext__()
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 76, in async_auth_flow
    await self.login()
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 111, in login
    token_data = await self._login_row_na()
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 201, in _login_row_na
    handle_http_status_error(ex, "Authentication", _LOGGER)
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/api/utils.py", line 57, in handle_http_status_error
    raise ex
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 163, in _login_row_na
    response = await client.post(
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1706, in _send_handling_redirects
    raise exc
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_client.py", line 1688, in _send_handling_redirects
    await hook(response)
  File "/home/pi/.local/lib/python3.9/site-packages/bimmer_connected/api/authentication.py", line 354, in raise_for_status_event_handler
    response.raise_for_status()
  File "/home/pi/.local/lib/python3.9/site-packages/httpx/_models.py", line 745, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://customer.bmwgroup.com/gcdm/oauth/authenticate'
For more information check: https://httpstatuses.com/401

When entering the same command directly in bimmerconnected, it works

regards

**Comment by MrJanD** [comment]
Try the payload without comma, as described in the README.md.
E.g.: 

> _'state' '[bmw.530d@mail.link](mailto:bmw.530d@mail.link)' 'password' 'VINxxxxxxxxxxxxxx'_

**Comment by manfi001** [comment]
I already tried it, also with double quotes, with and without commas, no chance


Sent from my Galaxy

-------- Original message --------From: Jan Deppe ***@***.***> Date: 12/5/22  23:08  (GMT+01:00) To: MrJanD/bimmer2mqtt ***@***.***> Cc: manfi001 ***@***.***>, Author ***@***.***> Subject: Re: [MrJanD/bimmer2mqtt] ModuleNotFoundError (Issue #1) 

Try the payload without comma, as described in the README.md.

E.g.:

'state' ***@***.***' 'password' 'VINxxxxxxxxxxxxxx'

**Comment by MrJanD** [comment]
Can you try it without the ' ?
E.g.: 
> state bmw.530d@mail.link password VINxxxxxxxxxxxxxx

**Comment by manfi001** [comment]
Published without quotes:

 

$ /home/pi/.local/bin/bimmer2mqtt.py

2022-12-06 13:44:16 INFO     Connected with result code 0

2022-12-06 14:20:54 INFO     car_execute: Mobility/CarName/cmd b'state ***@***.*** password VINxxxxxxxxxxxxxx'

Traceback (most recent call last):

  File "/home/pi/.local/bin/bimmer2mqtt.py", line 149, in <module>

    mqtt_handler.run()

  File "/home/pi/.local/bin/bimmer2mqtt.py", line 63, in run

    self.client.loop_forever()

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever

    rc = self._loop(timeout)

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop

    rc = self.loop_read()

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read

    rc = self._packet_read()

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read

    rc = self._packet_handle()

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle

   return self._handle_publish()

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish

    self._handle_on_message(message)

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3556, in _handle_on_message

    callback(self, self._userdata, message)

  File "/home/pi/.local/bin/bimmer2mqtt.py", line 54, in car_execute

    client.publish(TOPIC + key, returnData[key])

  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1247, in publish

    raise TypeError(

TypeError: payload must be a string, bytearray, int, float or None.
