### ISSUE TITLE
'state' command does not work

### ISSUE THREAD

**Issue by martingruening** [MrJanD/bimmer2mqtt#2]
I can use the 'horn' command properly, but when using 'state' the following error pops up:

2022-12-31` 09:14:13 INFO     car_execute: Mobility/BMW530e/cmd b'state <EMAIL> <PASSWORD> <VIN>
Traceback (most recent call last):
  File "/usr/src/app/./Bimmer2MQTT.py", line 149, in <module>
    mqtt_handler.run()
  File "/usr/src/app/./Bimmer2MQTT.py", line 63, in run
    self.client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3556, in _handle_on_message
    callback(self, self._userdata, message)
  File "/usr/src/app/./Bimmer2MQTT.py", line 54, in car_execute
    client.publish(TOPIC + key, returnData[key])
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1247, in publish
    raise TypeError(
TypeError: payload must be a string, bytearray, int, float or None.

**Comment by MrJanD** [comment]
Thanks, it shall work now.
You will now get a JSON string under the topic "... /status" as the answer to a state request.
